Repository recharts/recharts, pull requests merged in 2022-12, with the labels that each got.

#2923 Support keyboard navigation in pie chart
  package-lock.json
  package.json
  src/polar/Pie.tsx
  test/specs/polar/PieSpec.js
Labels: Type: Enhancement

#3088 Eslint: Update dependencies and remove redundant rule setup
  .eslintrc
  package-lock.json
  package.json
  src/cartesian/Area.tsx
  src/cartesian/Bar.tsx
  src/cartesian/Line.tsx
  src/chart/Treemap.tsx
  src/chart/generateCategoricalChart.tsx
  src/util/ChartUtils.ts
  src/util/Events.ts
  src/util/ReactUtils.ts
Labels: dependencies

#3086 refactor: begin refactor to jest while continuing to run tests in karma
  .babelrc
  .github/workflows/ci.yml
  jest.config.js
  package-lock.json
  package.json
  src/cartesian/Area.tsx
  src/cartesian/Bar.tsx
  src/chart/generateCategoricalChart.tsx
  src/numberAxis/Funnel.tsx
  src/shape/Rectangle.tsx
  src/shape/Sector.tsx
  src/util/ChartUtils.ts
  src/util/types.ts
  test-jest/setupTests.ts
  test-jest/specs/chart/AreaChart.spec.js
  test-jest/specs/chart/BarChart.spec.js
  test-jest/specs/chart/ComposedChart.spec.js
  test-jest/specs/chart/FunnelChart.spec.js
  test-jest/specs/chart/LineChart.spec.js
  test-jest/specs/chart/PieChart.spec.js
  test/index.js
  test/specs/cartesian/BarSpec.js
  test/specs/util/ReactUtilsSpec.js
  tsconfig.json
Labels: Type: Enhancement, dependencies

#3090 fix: babel warnings, remove unneeded babel config
  .babelrc
  package-lock.json
  package.json
Labels: dependencies

#3093 Chore/lint staged
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
Labels: dependencies

#3100 test: refactor and fix piechart jest tests
  .eslintrc
  package-lock.json
  package.json
  test-jest/specs/chart/PieChart.spec.tsx
Labels: dependencies, P0

#3112 fix: rename pr template
  .github/pull_request_template.md
Labels: P0

#3107 chore: use early return to improve readability of getAxisMapByAxes
  src/chart/generateCategoricalChart.tsx
Labels: P1, refactor

#3101 fix: points attribute spread onto incorrect svg elements
  src/container/Surface.tsx
  src/shape/Symbols.tsx
  src/util/types.ts
  test-jest/util/ReactUtils.spec.tsx
  test/specs/shape/SymbolsSpec.js
Labels: bug, P0

#3119 refactor: correct wrong spelling (ckeck, chilren)
  src/chart/generateCategoricalChart.tsx
  src/component/LabelList.tsx
Labels: refactor

#3121 fix: add some missing payload properties that might be needed in custom tooltip, parity with definitely typed
  src/component/DefaultTooltipContent.tsx
Labels: enhancement, P1

#3116 refactor: move filterProps to ReactUtils and refactor references
  src/cartesian/Area.tsx
  src/cartesian/Bar.tsx
  src/cartesian/Brush.tsx
  src/cartesian/CartesianAxis.tsx
  src/cartesian/CartesianGrid.tsx
  src/cartesian/ErrorBar.tsx
  src/cartesian/Line.tsx
  src/cartesian/ReferenceArea.tsx
  src/cartesian/ReferenceDot.tsx
  src/cartesian/ReferenceLine.tsx
  src/cartesian/Scatter.tsx
  src/chart/Sankey.tsx
  src/chart/Treemap.tsx
  src/chart/generateCategoricalChart.tsx
  src/component/Label.tsx
  src/component/LabelList.tsx
  src/component/Text.tsx
  src/container/Layer.tsx
  src/container/Surface.tsx
  src/numberAxis/Funnel.tsx
  src/polar/Pie.tsx
  src/polar/PolarAngleAxis.tsx
  src/polar/PolarGrid.tsx
  src/polar/PolarRadiusAxis.tsx
  src/polar/Radar.tsx
  src/polar/RadialBar.tsx
  src/shape/Cross.tsx
  src/shape/Curve.tsx
  src/shape/Dot.tsx
  src/shape/Polygon.tsx
  src/shape/Rectangle.tsx
  src/shape/Sector.tsx
  src/shape/Symbols.tsx
  src/shape/Trapezoid.tsx
  src/util/ChartUtils.ts
  src/util/ReactUtils.ts
  src/util/types.ts
  test-jest/util/ReactUtils.spec.tsx
  test/specs/util/ReactUtilsSpec.js
Labels: P0, refactor
