Repository recharts/recharts, pull requests merged in 2023-01, with the labels that each got.

#3129 Fix type of Brush Props
  src/cartesian/Brush.tsx
Labels: typescript

#3133 refactor: log and dom utils tests to jest and ts
  test-jest/util/DomUtils.spec.tsx
  test-jest/util/LogUtils.spec.ts
  test/index.js
  test/specs/util/DOMUtilsSpec.js
  test/specs/util/LogUtilsSpec.js
Labels: P0, refactor

#3139 Jest Migration: ReactUtils
  src/util/ReactUtils.ts
  test-jest/util/ReactUtils.spec.tsx
  test/index.js
  test/specs/util/ReactUtilsSpec.js
Labels: P0

#3265 fix: remove points attribute from SVGProps for Radar component for correct typing
  src/polar/Radar.tsx
Labels: bug, typescript
