Repository recharts/recharts, pull requests merged in 2023-02, with the labels that each got.

#3287 fix: remove deprecated alwaysShow
  demo/component/ScatterChart.tsx
  src/cartesian/ReferenceArea.tsx
  src/cartesian/ReferenceDot.tsx
  src/cartesian/ReferenceLine.tsx
  test/cartesian/ReferenceLine.spec.tsx
Labels: breaking change, refactor

#3327 fix: filter out functions in filterProps, remove type from valid SVGElementPropKeys
  demo/component/AreaChart.tsx
  demo/component/LineChart.tsx
  src/util/ReactUtils.ts
  src/util/types.ts
  storybook/stories/API/chart/AreaChart.stories.tsx
  test/util/ReactUtils.spec.tsx
Labels: bug

#3361 feat: add onResize callback fn
  demo/component/ResponsiveContainer.tsx
  src/component/ResponsiveContainer.tsx
  test/component/ResponsiveContainer.spec.tsx
Labels: enhancement

#3103 feat: add ability to set static domains to improve UX for toggling data
  src/chart/generateCategoricalChart.tsx
  src/util/types.ts
  storybook/stories/API/cartesian/YAxis.stories.tsx
  test/cartesian/YAxis.spec.tsx
Labels: enhancement, P2

#3397 chore: explicitly upgrade minor version of react-smooth
  package-lock.json
  package.json
Labels: dependencies
