Repository recharts/recharts, pull requests merged in 2024-02, with the labels that each got.

#4112 feat: add dependabot version updates
  .github/dependabot.yml
Labels: dependencies

#4111 Bump Vitest and Node and React and Typescript
  .github/workflows/ci.yml
  .github/workflows/npm-publish.yml
  package-lock.json
  package.json
  test/cartesian/CartesianGrid.spec.tsx
  test/chart/generateCategoricalChart.spec.tsx
Labels: dependencies, breaking change

#4184 chore: group babel and storybook dependency PRs
  .github/dependabot.yml
Labels: dependencies

#4186 refactor: remove ResponsiveContainer ref hack
  src/component/ResponsiveContainer.tsx
Labels: breaking change

#3859 removing support for es5
  .babelrc
  package-lock.json
  package.json
  tsconfig.json
Labels: breaking change

#4188 refactor: remove deprecated alwaysShow prop
  demo/component/ScatterChart.tsx
  src/cartesian/ReferenceArea.tsx
  src/cartesian/ReferenceDot.tsx
  src/cartesian/ReferenceLine.tsx
  src/chart/generateCategoricalChart.tsx
  src/util/DetectReferenceElementsDomain.ts
  src/util/IfOverflow.ts
  src/util/IfOverflowMatches.ts
  storybook/stories/API/cartesian/ReferenceArea.stories.tsx
  storybook/stories/API/cartesian/ReferenceDot.stories.tsx
  storybook/stories/API/cartesian/ReferenceLine.stories.tsx
  test/cartesian/ReferenceArea.spec.tsx
  test/cartesian/ReferenceLine/ReferenceLine.spec.tsx
  test/util/ifOverflowMatches.spec.ts
Labels: breaking change

#4192 fix: Ignore nullish values for domain of error bars
  src/util/ChartUtils.ts
  test/util/ChartUtils.spec.tsx
Labels: breaking change
