Repository recharts/recharts, pull requests merged in 2024-11, with the labels that each got.

#5211 Customized renderAsIs
  src/chart/generateCategoricalChart.tsx
  storybook/stories/API/chart/Customized.mdx
  storybook/stories/API/chart/Customized.stories.tsx
  test/chart/BarChart.spec.tsx
  test/component/Legend.spec.tsx
  test/context/chartLayoutContext.spec.tsx
  test/polar/PolarAngleAxis.spec.tsx
  test/polar/PolarRadiusAxis.spec.tsx
  test/state/selectors/axisSelectors.spec.tsx
  test/state/selectors/containerSelectors.spec.tsx
  test/state/selectors/dataSelectors.spec.tsx
  test/state/selectors/legendSelectors.spec.tsx
  test/state/selectors/scatterSelectors.spec.tsx
  test/state/selectors/selectChartOffset.spec.tsx
  test/state/selectors/selectors.spec.tsx
Labels: breaking change

#5219 feat: remove both names and values from the tooltip if formatter returns a nullish value
  src/component/DefaultTooltipContent.tsx
  test/component/DefaultTooltipContent.spec.tsx
Labels: breaking change, Tooltip

#5217 refactor/fix(ResponsiveContainer): remove display name and isElement checks
  src/component/ResponsiveContainer.tsx
  test/component/ResponsiveContainer.spec.tsx
Labels: breaking change

#5227 refactor: remove unused generator code after composedFn migration
  src/chart/generateCategoricalChart.tsx
  src/polar/Radar.tsx
  src/polar/RadialBar.tsx
  src/util/ChartUtils.ts
  src/util/ReactUtils.ts
  test/util/ChartUtils/getBarPosition.spec.tsx
  test/util/ChartUtils/getStackedDataOfItem.spec.ts
Labels: breaking change

#5231 RadialBar uses its own implicit radius axis of type=category
  src/state/selectors/polarAxisSelectors.ts
  test/chart/RadialBarChart.spec.tsx
  test/polar/PolarRadiusAxis.spec.tsx
  test/polar/RadialBar.spec.tsx
Labels: breaking change

#5235 Polargrid axis ids
  scripts/snapshots/es6Files.txt
  scripts/snapshots/libFiles.txt
  scripts/snapshots/typesFiles.txt
  src/context/chartLayoutContext.tsx
  src/polar/PolarGrid.tsx
  src/state/selectors/axisSelectors.ts
  src/state/selectors/polarAxisSelectors.ts
  src/state/selectors/polarGridSelectors.ts
  src/state/selectors/polarScaleSelectors.ts
  src/state/selectors/polarSelectors.ts
  storybook/stories/Examples/RadialBarChartMultipleAxes.stories.tsx
  storybook/stories/data/Page.ts
  test/polar/PolarGrid.spec.tsx
  test/polar/RadialBar.spec.tsx
Labels: breaking change

#5250 Fix labellist data key type
  src/component/LabelList.tsx
  test/component/LabelList.spec.tsx
Labels: typescript
